version: 2

jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            export PIP_DISABLE_PIP_VERSION_CHECK=1
            apk add build-base
            apk --update add py2-pip
            /usr/bin/pip2 install docker-compose
            docker-compose --version
      - run:
          name: Start Container
          command: |
            docker-compose up -d
            docker-compose ps
      - run: 
          name: Test
          command: docker-compose exec app ./bin/rs
      - run: docker-compose down

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build