version: 2.1

executors:
  my-executor:
    machine:
      - image: circleci/classic:edge
jobs:
  build:
    machine: my-executor 
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: test
          command: docker-compose exec app ./bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down

  deploy:
    machine: my-executor
    steps:
      - checkout
      - run: docker ps
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      - run: 
          name: heroku maintenance on
          command: heroku maintenance:on --web ${HEROKU_APP_NAME}
      - run: 
          name: build and release heroku container
          command: git push heroku master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --web ${HEROKU_APP_NAME}

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master