version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: test
          command: docker-compose exec app ./bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build