version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: test
          command: docker-compose exec app ./bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      - run:
          name: specify heroku app
          command: heroku apps:info --app ${HEROKU_APP_NAME}
      - run: 
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run: 
          name: build and release heroku container
          command: heroku stack:set container && git push heroku master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master