version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      - run: docker-compose -f docker-compose-prod.yml up
      - run: docker-compose exec app ./bin/rspec
      - run: docker-compose down

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build