version: 2

jobs:
  build:
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            export PIP_DISABLE_PIP_VERSION_CHECK=1
            apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make && \
            pip install docker-compose
      - run:
          name: Start Container
          command: |
            export DOCKER_HOST=127.0.0.1
            docker-compose up -d
            docker-compose ps
      - run: 
          name: Test
          command: docker-compose exec app ./bin/rs
      - run: docker-compose down

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build